### ISSUE TITLE
Finish Trajectory Orchestrator

### ISSUE THREAD

**Issue by epshteinmatthew** [frc3268/ValhallaLib#4]
Trajectory Orchestrator should to be built out to the point that the robot should be able to follow a path

**Comment by Chargde-Porcupine** [comment]
Done to the point of being untested, but implemented

**Comment by fernir3268** [comment]
No rotation working, but everything else is ok

**Comment by epshteinmatthew** [comment]
Upgraded to high urgency. We have some kind of trajectory following working, but it needs to be tuned(PID). This will be the core of our auton. Also need to fix the problem with it going backwards(why?)

**Comment by epshteinmatthew** [comment]
closing
